name: Run Playwright Tests on BrowserStack

on:
  schedule:
    - cron: "5 * * * *"  # Runs every hour at 5 minutes past the hour
  workflow_dispatch:  # Allows manual execution

jobs:
  browserstack-playwright:
    # Only run if repository variable is true
    if: vars.RUN_SCHEDULED_TESTS == 'true'
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests on BrowserStack
        run: npx browserstack-node-sdk playwright test --debug --config=./playwright.config.test.ts